### ISSUE TITLE
Blender 4.0 compatibility

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#202]
https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API
- [x] 'ShaderNodeTree' has no attribute 'outputs'
- [ ] replace bone groups with bone collections

**Comment by ssbucarlos** [comment]
ill get around to this after i get home today

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: SMG ***@***.***>
Sent: Wednesday, November 15, 2023 2:22:00 PM
To: ssbucarlos/smash-ultimate-blender ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssbucarlos/smash-ultimate-blender] Blender 4.0 compatibility (Issue #202)


https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API

  *    'ShaderNodeTree' has no attribute 'outputs'
  *    replace bone groups with bone collections

**Comment by ScanMountGoat** [comment]
It might not be possible to do this in a way that still works with 3.3-3.6 because of the bone group changes. If we need to break compatibility, we can update the minimum version to 4.0 to avoid any confusion.

**Comment by ssbucarlos** [comment]
not sure how many other plugins are affected and how many users are going to be remaining on 3.6 LTS, so for convenience ill add a release for the last 3.6 compatible version

**Comment by ScanMountGoat** [comment]
A release works well for keeping a snapshot of the current codebase. Blender 4.0 raises the minimum OpenGL version, so not everyone will be able to upgrade. They'll probably be switching to Vulkan eventually.

Thank you for looking into the compatibility stuff. Let's hope Blender 5.0 doesn't break everything :)

**Comment by ssbucarlos** [comment]
Im getting around to it now, seems like theres also changes to the principled shader as well. ill try to see if i can get this done today.
